---
- name: Configure DNS servers and clients
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - bind9
          - bind9-utils
        state: latest
        update_cache: yes

    - name: Copy zone transfer key
      copy:
        src: templates/named.zonetransfer.key
        dest: /etc/named.zonetransfer.key
        owner: root
        group: named
        mode: 0644

- name: Configure master DNS server
  hosts: ns01
  become: yes
  tasks:
    - name: Copy master named.conf
      copy:
        src: templates/master-named.conf
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640

    - name: Copy zone files
      copy:
        src: "{{ item }}"
        dest: /etc/named/
        owner: root
        group: named
        mode: 0660
      with_items:
        - named.ddns.lab
        - named.dns.lab
        - named.dns.lab.client
        - named.dns.lab.rev
        - named.newdns.lab

    - name: Configure resolv.conf for servers
      template:
        src: templates/servers-resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: Set named directory permissions
      file:
        path: /etc/named
        owner: root
        group: named
        mode: 0670

    - name: Ensure named is running and enabled
      service:
        name: named
        state: restarted
        enabled: yes

- name: Configure slave DNS server
  hosts: ns02
  become: yes
  tasks:
    - name: Copy slave named.conf
      copy:
        src: templates/slave-named.conf
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640

    - name: Configure resolv.conf for servers
      template:
        src: templates/servers-resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: Set named directory permissions
      file:
        path: /etc/named
        owner: root
        group: named
        mode: 0670

    - name: Ensure named is running and enabled
      service:
        name: named
        state: restarted
        enabled: yes

- name: Configure clients
  hosts: client,client2
  become: yes
  tasks:
    - name: Configure resolv.conf for clients
      copy:
        src: templates/client-resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: Copy rndc config file
      copy:
        src: templates/rndc.conf
        dest: /home/rndc.conf
        owner: root
        group: root
        mode: 0644

    - name: Configure MOTD
      copy:
        src: templates/client-motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
